apiVersion: ENC[AES256_GCM,data:3Gw=,iv:qf21sowje3M1xypP1gZHBeZ53rFsnSlYMrbRqF0YXpY=,tag:czYtd2mPaFfort6J3djkww==,type:str]
kind: ENC[AES256_GCM,data:cgY+GCdv,iv:CYElplJkcpm0J/99nu5pV34ksUS1A69mr94FF2fwnn8=,tag:Lh1PPwNS6SW5f9ofZ0pfBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9/Dld24UYXUcXAc=,iv:p5ZzFUp62EnD2qQpVhbPOzqZR2x+F0yI/31lsXIS9CE=,tag:osnwUkn2/UrIiu46tYEomw==,type:str]
    namespace: ENC[AES256_GCM,data:0PW4s1E9G6To7b4=,iv:I1A/VVtnvr6eFtY4/fM0/xdyXlznsxnNhIqwql7W/zc=,tag:e87kR5DKB8OYTn+2Z/Ujuw==,type:str]
type: ENC[AES256_GCM,data:ZbBFer98,iv:esTlym9qRkP6QZv+PrqrntwMVkQmKDDLdrLCSWWYuHk=,tag:8jfx6jBFhJY5SFFn9iA8Qw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:xD6SVMmT,iv:4erevJxNioBWxteUg03exOR55WUVkZJX42iOWvAoct0=,tag:mXneukXR64NrbJOgfIdgWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ3p0a3BrTnlkN2xhTTN0
            NFVqbHRrdXNXZStMSjJTSFpaUE8wc1BQYmwwCkdXREQrVXZvZUxoVHBEY0NMcXcw
            Q2Z2ejFhZzY4SVRlZ2xESlFUTCt6NWsKLS0tIFFTTkpaYWtYQzMrcE4xT0ZTNTE4
            eFh4VGI3WXRUMkc0UERybnkzWU5MZUEKVKRkKchYAFlddauUsyf2T1zTtc9eV8Lc
            PR4sWl5BL5Le+aEblQfVPxjp62J6rTCCkC5twOhaUxPj6uBxTV/73A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1guvkjxc9cp2593z67tzs8dtr4ss2wncertclj0cvuzarg8gj6d4svw8pzd
    lastmodified: "2026-07-08T09:07:15Z"
    mac: ENC[AES256_GCM,data:liC0VIbsTddxxkgp+BxEvtfrh6f9bTXZjmSjypHpXx14US8gHptbySJaxTt3mi8b+jpzvvaW59hCc58ztjBg4HQeGCVqo9PPYbACl9CkSQPb/jUTRMdGnDdlEGKNeQG6VIS7x5yUGlPXTdt+UmLHcKvaGpuaU98welLmc1KNeXo=,iv:t7jYdFj7lor5osZQlVIkYeLsLUKAqm2nMvvn+cr9Mq0=,tag:+XsnlHTyAskLT0x302kMnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
