apiVersion: ENC[AES256_GCM,data:E7M=,iv:vmPsLI9A5akJOgijC4QDqKXJd43yj7ROfHuMa0ihU68=,tag:5uroXI3ld3c3C3h14qkz4A==,type:str]
kind: ENC[AES256_GCM,data:L7uD2ygf,iv:avFKkuWNH4Eg43KblFMw6HgYdZhm9oddl0WjKnWzcJE=,tag:L8M8IbjLJ95kAtqqDUOckw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AV0slt/kMI9oZW17,iv:Fdv1rio5HsXRpqeKoVJwjOFW2COBSioNAK+dZGFGWeQ=,tag:kDp2iA9yAJTMV0SIj3SAgw==,type:str]
    namespace: ENC[AES256_GCM,data:ENONASTIchqbQGtg,iv:IzyKmfWOLMc3jvYsQBQ0cnhfDcVJ2XA5XKQQCefMhKs=,tag:iKNAIKuecxJ1z1yE+F/V9A==,type:str]
type: ENC[AES256_GCM,data:nH/6rmHM,iv:gFzWpGLUp3y1pAbNjIqDfucqKcESu0RwJZGfAatitV4=,tag:n52PORcvbGek/HvTk+Phww==,type:str]
stringData:
    acme_email: ENC[AES256_GCM,data:Jnx3Ung0GjZ5OekU0p3IVw48D6QoNA==,iv:jqbokjqAT+a6CL7kjB8SNnikcSXBY/K+3j0Gep9oCBE=,tag:UD/sblDXI/YUy0Zxvrii2g==,type:str]
    gts_key_id: ENC[AES256_GCM,data:pGmZyTMcCaEKBeGh2rirU8/EqK/lRjspG278P+kZpf8=,iv:08BNoGM1FZAuK76JvalHvHWbHjj+tsQJb6KkGWMlx7s=,tag:6UXOeTx/qLk3DjYKyR7dMw==,type:str]
    gts_eab_secret: ENC[AES256_GCM,data:19HphqQ2Qx4F/BGjhHdeJxeMiNOQ0rihhHYmycAPVj5ZVzYNuC98lsTOJWSjaT9ebnlfSnKjuQP5YBIm2XSf55PuwXZ9xFzfkbO2d5QfD/ZebX8u+pLA,iv:gsePbMgGZ6Jny7nSUZt1DtBRSgXw0lj6mGHrH6cmxJA=,tag:KcmCRaxHDLcmLahRfZSfJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeW1Rczl0Z2l2QjdWL3BO
            dUR4cDRuazdObWJ5dTlzWmdiRHJsTGNjaDNzCkdvTW42NHdMemg0b3RGZ00xaGo2
            M212S1pSeUxTSkF6RWk1bjBZaklzY2sKLS0tIHIwdUNHUVAxV3g0VDNScitlcXBI
            M2kvSVZBaXZUbVIrZm9WaGNJbWJNL0EKgVJd1XHMlXxuS6P0ajPKmItYCM9gU8Pj
            gKhIpGv/A61nLu6967vtR/2VKVbMTUeThn7POktU/c/Evct8voiIbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1guvkjxc9cp2593z67tzs8dtr4ss2wncertclj0cvuzarg8gj6d4svw8pzd
    lastmodified: "2026-07-08T08:38:40Z"
    mac: ENC[AES256_GCM,data:4Toqmui2iJq2wM5PIlYxRcm3x7umVDPrgtuTaInVHhnmaEhrQs9SFrQQpxZ1VZufXCcVVFFSBJcLTudRBGwtgLB6n46afvDYe6ESZ7MJKNC7baMXJypC9cOXy3AK6bojTzpsxE3xf3EawpyU7Rr1mRwUxhM6fiWzdk2W96NyB1Q=,iv:jOio2P9gyB1uTHYDOznUIKc9JN1KJYdA0GVWTCdXql4=,tag:FYh3IRi/QyJZnJZVPyf7+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
