apiVersion: ENC[AES256_GCM,data:E7M=,iv:vmPsLI9A5akJOgijC4QDqKXJd43yj7ROfHuMa0ihU68=,tag:5uroXI3ld3c3C3h14qkz4A==,type:str]
kind: ENC[AES256_GCM,data:L7uD2ygf,iv:avFKkuWNH4Eg43KblFMw6HgYdZhm9oddl0WjKnWzcJE=,tag:L8M8IbjLJ95kAtqqDUOckw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AV0slt/kMI9oZW17,iv:Fdv1rio5HsXRpqeKoVJwjOFW2COBSioNAK+dZGFGWeQ=,tag:kDp2iA9yAJTMV0SIj3SAgw==,type:str]
    namespace: ENC[AES256_GCM,data:ENONASTIchqbQGtg,iv:IzyKmfWOLMc3jvYsQBQ0cnhfDcVJ2XA5XKQQCefMhKs=,tag:iKNAIKuecxJ1z1yE+F/V9A==,type:str]
type: ENC[AES256_GCM,data:nH/6rmHM,iv:gFzWpGLUp3y1pAbNjIqDfucqKcESu0RwJZGfAatitV4=,tag:n52PORcvbGek/HvTk+Phww==,type:str]
stringData:
    gts_eab_secret: ENC[AES256_GCM,data:19HphqQ2Qx4F/BGjhHdeJxeMiNOQ0rihhHYmycAPVj5ZVzYNuC98lsTOJWSjaT9ebnlfSnKjuQP5YBIm2XSf55PuwXZ9xFzfkbO2d5QfD/ZebX8u+pLA,iv:gsePbMgGZ6Jny7nSUZt1DtBRSgXw0lj6mGHrH6cmxJA=,tag:KcmCRaxHDLcmLahRfZSfJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeW1Rczl0Z2l2QjdWL3BO
            dUR4cDRuazdObWJ5dTlzWmdiRHJsTGNjaDNzCkdvTW42NHdMemg0b3RGZ00xaGo2
            M212S1pSeUxTSkF6RWk1bjBZaklzY2sKLS0tIHIwdUNHUVAxV3g0VDNScitlcXBI
            M2kvSVZBaXZUbVIrZm9WaGNJbWJNL0EKgVJd1XHMlXxuS6P0ajPKmItYCM9gU8Pj
            gKhIpGv/A61nLu6967vtR/2VKVbMTUeThn7POktU/c/Evct8voiIbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1guvkjxc9cp2593z67tzs8dtr4ss2wncertclj0cvuzarg8gj6d4svw8pzd
    lastmodified: "2026-07-09T07:09:08Z"
    mac: ENC[AES256_GCM,data:Z+pPm5XbQR6p0BDdu8+/6mBbhh0zfIs22hVWoH0kB+owj4/gY5r/I91l48BhGF3mCC1wW4mxcK4srMSH/syQP633hIvWs5Kvbapy/Gykakg52V23foWcW8RhXg6FKPyxW752GV57WszQmJPVlv1TiTdGb6SRk4GZ7+cZ21txcKs=,iv:hDnZOQ/DX2h1OFL1THOPzU0VLsnKPf4LaoqRZTFcO80=,tag:992h8BkfEesIBc2baJ3xCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
