apiVersion: ENC[AES256_GCM,data:3Gw=,iv:qf21sowje3M1xypP1gZHBeZ53rFsnSlYMrbRqF0YXpY=,tag:czYtd2mPaFfort6J3djkww==,type:str]
kind: ENC[AES256_GCM,data:cgY+GCdv,iv:CYElplJkcpm0J/99nu5pV34ksUS1A69mr94FF2fwnn8=,tag:Lh1PPwNS6SW5f9ofZ0pfBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZyEJINCbfkobVA==,iv:SFDYHSJrKG7yQYvcBS0Byk0jSd3knxgMwUEP38yBkWY=,tag:dF+yB4tf3WDvS3/VkvrEcA==,type:str]
    namespace: ENC[AES256_GCM,data:eqs8vqeaz0sXxaHP,iv:a2TJ+uksrqsSu9j6a3uIORg6mr6S7IZqcUW4SFGGb1w=,tag:wsEhvgymtopBTkjAVbfFWQ==,type:str]
type: ENC[AES256_GCM,data:ZbBFer98,iv:esTlym9qRkP6QZv+PrqrntwMVkQmKDDLdrLCSWWYuHk=,tag:8jfx6jBFhJY5SFFn9iA8Qw==,type:str]
stringData:
    api_token: ENC[AES256_GCM,data:lgX+8QYegr4ZxCuKyhPdFxwINQu4JOKlFkqrMJ27E/wka+fRB8okTmPQyjiz1p+YQkLbIa4=,iv:T+MO+vOYzjMAanlk3eV/JumsmvHmRj5jsNu1wrwKYk0=,tag:L+tSIC5WMuKWAbsC0K9ySw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTTRXZXFMZHNMQ3pSSHBr
            cVNoK3pUVzAyRTNDL3M3V201eEdDYStnSnc0Cks1TmFIOVpXWTAwOUZHQ0dMRjZR
            bnY1dWxWUzdzYWltempNQ0VyNEwxWU0KLS0tIGFWY1pYTGF1NDhuSkExaFJKS3E0
            UEhNNnhxakQvaE9UeHMvOERqU0RERWsKzg6Q4B1OhpGeDqvxcday4hZpudOSMk0d
            uxKbhpmxzgHX0yHqM5iyj38iMXJJI5+TU+Q/0+VLRKQJR0rc4o4Y6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1guvkjxc9cp2593z67tzs8dtr4ss2wncertclj0cvuzarg8gj6d4svw8pzd
    lastmodified: "2026-07-08T08:36:23Z"
    mac: ENC[AES256_GCM,data:7L/yb5M8cdi6OLB0M0jyxXpUeO4YEgN2yKcnr5F8qMhif8qu6NzMM2X3vS+JFHHoueF+P2gjXm11Bn4MQjVMTZmvEUgYAAO6LWf1W24Yb7dvel1juVtGVGyeeUX180vi98+evOYHBJi98xlGq0AdV3/A8UD6i5JG3CuyzVOkXoY=,iv:Rgh9jiIHMlCHnxAEXP/zWb5dkwa2GE3fCZgTcjlkMZ8=,tag:sQjIIpx1I2sm+iGID1KHjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
