apiVersion: ENC[AES256_GCM,data:3Gw=,iv:qf21sowje3M1xypP1gZHBeZ53rFsnSlYMrbRqF0YXpY=,tag:czYtd2mPaFfort6J3djkww==,type:str]
kind: ENC[AES256_GCM,data:cgY+GCdv,iv:CYElplJkcpm0J/99nu5pV34ksUS1A69mr94FF2fwnn8=,tag:Lh1PPwNS6SW5f9ofZ0pfBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZyEJINCbfkobVA==,iv:SFDYHSJrKG7yQYvcBS0Byk0jSd3knxgMwUEP38yBkWY=,tag:dF+yB4tf3WDvS3/VkvrEcA==,type:str]
    namespace: ENC[AES256_GCM,data:eqs8vqeaz0sXxaHP,iv:a2TJ+uksrqsSu9j6a3uIORg6mr6S7IZqcUW4SFGGb1w=,tag:wsEhvgymtopBTkjAVbfFWQ==,type:str]
type: ENC[AES256_GCM,data:ZbBFer98,iv:esTlym9qRkP6QZv+PrqrntwMVkQmKDDLdrLCSWWYuHk=,tag:8jfx6jBFhJY5SFFn9iA8Qw==,type:str]
stringData:
    api_token: ENC[AES256_GCM,data:lgX+8QYegr4ZxCuKyhPdFxwINQu4JOKlFkqrMJ27E/wka+fRB8okTmPQyjiz1p+YQkLbIa4=,iv:T+MO+vOYzjMAanlk3eV/JumsmvHmRj5jsNu1wrwKYk0=,tag:L+tSIC5WMuKWAbsC0K9ySw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHlrRFlTV1Qv
            K05GT1BkSEhkSFBTTlJqVm0vdnZaQVUxVmxzY1psdlI3UnlrenlUei9va3crTmFs
            UG5RbFRUL1g5b2s0UGlxSDhYZ0t1S3VCZDBIM2FXMFlqSUVHbEhMcVA5MWk4U2Np
            S2kza1FhQjFLcUF3ZzJFUDhxV2laVk5QZFdDY2x1Z09La09hYXdpZHp0dEFqcEV3
            a3p0ZzIxU0JNL0Q1Z0c1eldjRzZNNURXOHBNYWdYSGxkdTEzbTVxd1gvT1Y4azUw
            bVJVTnptM2JNQmNrT05LQW1LcDlWZ0hVa2s3Z2t2Z1JHZGk0NGcwT2pxTXVtR2hZ
            aGc2WkNmSCtudDhLV0dVMWhDUks4WWZsMHZrd1ZpRzQ1ZnE5VUpqRXFXVTZlaGk3
            UG43NU1jOGRDaHJDNnM5ejcraXJ0ellyRnAxTUtNUDlNOG5BMmFtVklQYkJORVQw
            b3RoblZhWVo2WXZYRUVRNXJVZ1dGY1BhbGgzZHlUK0ttdkx2MEpxYURBM3VpNXRR
            ejhidVlvTFM5Tm9hZFZvT2NPN2Z0SC9tTmY0MGhaOHMvTjNPK1ByRk40aTdERXNJ
            NVFTZ3BnOWU5MEpDbmlTT1lZZHBKYWh4TXFheGRjd0E3MUdGRlBaeCtqTGVqVUk4
            ZWFkem8wTkRsSXFqa0NWZnlVMzMyVHFyUjZiNElOYTExbGVHZDFUQWNGalNpNjNY
            ajVNaEhvZkp2eGlhMWRxZ0NTZjRFbDdwMmhYb1E4SmdTdjNoM0t2T0FTREpWYXNR
            VXhEbDZIbU4zKy9tRU9YMDAvRm9xZlFUaFJlQ0FGWjlYY0FwYmg2K3AvWXVOUEcx
            RXJzeldKQWpSZEFHTDdPOU5hT0VEUjl1T1RKQU1VT0JSWkhOYisrRlBVdnVZeHdF
            Z3BvRXUwVmloK0RuM3IzUEhzNnBpQlN3UWNnSGo0UzJxd25MUHFab2NBQitBTy9X
            cFp0b044eE53cU1uQ1pyeFE0bHV0VHFCOWkyNHp6bGJEY1huaVRRT0kra2xCNmQ1
            NVVCQUNSV1Y5Yzlqcjdabk11b2JhZ1RIQStmOFYyZDBqeXI2RmNpRnEvajIwOXlH
            MVZzdlAwVG43V3NKZFdVckF3MVlRUU9QV3hKUjMrT095UUFtNDFFbXpqUHZmNVI5
            TDFGclZ4MmZmNFp0MFNFcTlIQ3NBUEE3Z08vZDVHb3Jhc3UzYTVBdkYrdFRGQStZ
            b0JVeTlORFJOUzcwekFuNlNaSHplb3Nvc2hpNEF5d25pak4vMEc1L3dXNElVY0hF
            T25uMTVjYjNNR29KYi8vRW9pZk9TalBXWVAxMW5JblhjaE9oay9qQ1c2WWJUN0o2
            dndkZTZkdWJDTEhQVkhuL3JyUnFKUkFNYjVDVEdCNUJscVR0cEcvUmR3R2pLSnBi
            V2xLTXJ4L09adkZzOWhBOENFdUZlVXJKODBUY05idU9zTFFjelJXdWRhT2YyTERO
            eCt2RUxaUUdjWDJrOW93eXlmUy9HTVlJRGdDY0VFQjFJOHdFaElISmU3TEp6d0F6
            WHdCTGJMYnBvdzJoNUxhRmVZeDY4Nktua3I4M2VQRUN0RHZRNnNBR2dpWGp6TlQ3
            STkzY0YxVzRscGpyaE1vcStuSXhZRm5aeE1tYi8xdzRsKzJaNnJwMEJyOUx4UGRS
            ZVNmK1pqd01MSUM5M0I5SUl3YkEwaFpCa1djSE1vMGlCMzZ6TEpFL0NFOGNXMGNz
            RkE0LzVsVXY2Z212VitFcVc3NFU2QXZaQ1JkVytrSTFBNFkzSTN6YXNpU2QyOC90
            TG8vcWJrMEhBaE1OMWRUOTRZMW56VG82S2pqMjRGNmJydTNmT1lad2Urb3MxeS9N
            OTJTSllsQ216VDhqWDJhRFBqV2hMVk54eXNxMVdZMVhkWm5CL3FTa016QnJuRi9P
            Q3l0dXhlY3FBS2ZnOUdKNmx4bm1Kc0NFWWx4UUc0U21YbkNCL3B1UmYzVCtRdwpt
            MFhFVk9GRWJBTGMwMVF0NGxSRG1maURWcEdCWE1EcHMwbUhyUm43Yms4Ci0tLSBl
            U2s5TXZjcktsWnNobTJ5NHdXeWMwWERIVkI4dnNOZUoxMC91eHBNZHVnCggvmpb9
            COjlvmHRo4vht2339h5cdroEtZsKVNgP7BwQav96gicUP9pHHLqsVbLrTMqeuZwr
            1Ah5JBKsjPWZGYA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1vtm9msr3ck8wgmaeu7k7tfny0vr2preuk2vwj59jl395ta2p64tvxp0383das6rnk2d036g84fy4negsps3erxr4546lr5f4r0t892vkdzzrnzx4ca83v4anqwx8udgfq64ckyz8c7qczjga7rdn5z9hsfkazm5ek6w564fcffaskj7k4kld0t8wtvj5xp2074dtewlgs4k8z32k8sdawsasrupj5jaggde5qwpw3ytfefylrmgtwwqqfktfz83tut8puka97lf5kg7230rnznq69vjpl2qz40mchqyyq0k3v8fq9ryruk5tgsaq7v3trgv7gsura9nygh9svwxzh2rkkeqfepesfqpjzwqd3xaeuv43rtfd30fxwcv3zvyk4au8j5kn03p48vhtsx7fwuzkj9v6ttts5jk9dtflz9snpf94kqpy889ftjzjqkepv3x75yjwd56ryk73h05lk3fgxw876fdwur53cfy6jxk7y8ef3vft98q9u99qydjg50a5n8yfwxfpl3kyxhegdpw3dq8kzlz4cddx8acgz64tv243867ndfpvql9xww50xpsgsc688v8ntfwuykhncww8l9t63vp5wqattj5q2en9smz6tj7q97z6gdcxyqpl5xj4zxz4td64tze6tyalv0m2xswuza2p3s2hu9m4k2e5g28xey0h5vmfgacfg42g0jcurw2r592jvyrrweqk9j2v45sf40kpgcmfs9elagdzf236w2w8dtptax9j4ya5fkq54xxzykd6geqg0jpnk24jtzs4jrtrddmyyaud6ueklvc6pudp0ehs085jcvwggcylfwzl40mm02jm0m7u9yq05dzy7g6mdsncs0e43un4s4043y6q24dhlqtnnjq6vjn2zsdsdg4p24yrsmcuqctnytenq390lvs3dgj8kl66rmgvdkzcszxwlxk8lg3skt2cwr5ee4u22nh75j5m85paem26kxmsd4wlz96yvgp59avpeety7vz38wq3y3slsgfq249hek9k5a4z9xdc2jwx4xuu49vz8um5lw7srqnvv7030x7z0g5ayx7xrwxrj28x5ujqsvzl0qgq29smxcxjwsh2yfwhsecnsjf7czuudq0qcxeyzvym7zvs5pvmuxu5zt4209an0yj6v9405gvndsffk5f59ah9g6dwyaztmeuzpesm539xh49dpn5jhz26nqdmgvd6whdmfmuysszv03rn65ckqv53cj48deqh5r4tudm9ax4n7ypgmpuxyj3q50z38pwehafgw3nr7dcrzdze3tsh9y36ray9yyt2pyytqsjrkjkc774q0w4zgv5nps3v449q29alzu6adw4yg0dr0epzk5hnsdklyj2nh3gx65yges0sgxdp98l829gj5sefe7eyc5khd99zrsl46txcg3kvqzwv6sf8ctjvw77sl90rmp3q3vnxg678kf738dwpvpgxxd9rhzeqrtduy9xm3y4dygj5ppmcsmvjsfapc9zjjwl8zuypypem604ezlatkhu7jxx5cshncqjsc96pf4lswppj538euzvd3xr84xyvz4psheyjksq72y2re7nfyx4uv8u6yc4wz5ljxfmuwkck9cepn4p4vn8n5gjde32mpvmd3dapd4kkvyujxhlq4g2k5g3lyegza4kqcqxdn3v88w4qf52tr0666jcks47ezavy6am9qymytpsh38lyr0aszfxkedt6nwe3q69ecu3urypuw9fw9skawv47jlesqgepjed9trfqmryc5w4wv528k3eyvwswx95pj7q0f5f0vvqxltlprvfwjcfjrz3su36kx59vlg8hq2gnjf2nmq0k7qqr99zvsf5xnvlnkhjvn0k0pcymkf9stnu72l4xavumuq7senlfqhrr8n5q5k04qyet5jx30hp4tq74n8vg
    lastmodified: "2026-07-08T08:36:23Z"
    mac: ENC[AES256_GCM,data:7L/yb5M8cdi6OLB0M0jyxXpUeO4YEgN2yKcnr5F8qMhif8qu6NzMM2X3vS+JFHHoueF+P2gjXm11Bn4MQjVMTZmvEUgYAAO6LWf1W24Yb7dvel1juVtGVGyeeUX180vi98+evOYHBJi98xlGq0AdV3/A8UD6i5JG3CuyzVOkXoY=,iv:Rgh9jiIHMlCHnxAEXP/zWb5dkwa2GE3fCZgTcjlkMZ8=,tag:sQjIIpx1I2sm+iGID1KHjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
