apiVersion: ENC[AES256_GCM,data:29I=,iv:E8PjX5GelL9Ia7jLtDNrGExwQuUsJhYTpooVs8w8Snc=,tag:bKWKw47DVyVzGpot/6NYqw==,type:str]
kind: ENC[AES256_GCM,data:msTZtGZO,iv:hd5TPO2w/sROmxU9WS7Ju31mcysYSJ/5Gu9ProoF6h4=,tag:7V6UNnTHUit2zkQT7uj8eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wwJbMDZwb3igyTTh,iv:tuQ8Kv7KZCf+3nQA3lEE/2Xeqwd24lM8UFeC/AUI8FY=,tag:MrPPwFLRplhYP+flqbGaaA==,type:str]
    namespace: ENC[AES256_GCM,data:W07BZJrLFLMqftU=,iv:leFNJX2H0wun4uPse9jk5Hlulj84+csrUnz4MV9MSYw=,tag:/3LA2lxyB/8mkGGfImt8bA==,type:str]
type: ENC[AES256_GCM,data:OBpnTdFV,iv:ccKodn6iq0GxeKv6Rg3vfF6Zae8bQwmy+ZGgwqJ5Kc0=,tag:KE9/8D/cWq1ekzz/ohn1tw==,type:str]
stringData:
    acme_email: ENC[AES256_GCM,data:8de2W9wMYQLzAlfDeZqQSePOO1XO8A==,iv:7VbxdLh62thxdYfGGZn2tORD5gRlyWlgzcyV/zNA3SI=,tag:b0gF3PT479HrIqqy2TBX3g==,type:str]
    gts_key_id: ENC[AES256_GCM,data:wzMJ73fuQJqVXOD8cqWE3ZjrOuR6XGtJUUkwh4hOpQk=,iv:n3h4vhmUNa64vOuWqC8eQSlN5bZ4w94F0koKqL+ExZU=,tag:5NgXIbarCvRZjRdys2UKOg==,type:str]
    acme_email_stg: ENC[AES256_GCM,data:/vtAym04MdWp0eVqxqSgoIX4RBc2hw==,iv:fgOxG8LWhR4mIqbJikcoFz5MS54skgO2wwpXOY2b/xE=,tag:iE2HpiCqal1QBJ0jnvabYg==,type:str]
    gts_key_id_stg: ENC[AES256_GCM,data:emhATH3ERl1cDwdkTvWBfFCwqL45e93EOos/4MycnXM=,iv:TBGjgUc4pvbdw3Z+QROeHQq9Rf+QB1REBSc8jjboD70=,tag:hO1DIkkOVEcGUlbBkiGm5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMEc5M2UzQWNxeThCWk5L
            eWFIRk5EYTF6SWYyTEtlOExucnRTMmdJdWtBCnA3NkQvM0pmWm1QSFpsdGlBZlgw
            NUdJZ25vN1dkUW1aYXlwV2Z0MGVTZEUKLS0tIDNzR1hRejg1OTcyZkhnaW5rR0xv
            SlBzblFxNDJBdkNmbjY1Zmx1bjV6YXcKrDQ1ypbAhdf03dQxrHpBQ0HuFWbp3cVv
            q8j7ormpwkmLLir7NAGWt0C+s48jdLX+1VthR5gdyyg0MZ7bjEGvIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1guvkjxc9cp2593z67tzs8dtr4ss2wncertclj0cvuzarg8gj6d4svw8pzd
    lastmodified: "2026-07-14T07:40:53Z"
    mac: ENC[AES256_GCM,data:eo6RbRdRB4F/m05mI8qbHdjqJBB/vve62gE1VxGh44USc5FrIkiQe/2NSz8VUy5BQ2FdcfCoMpBQQuEXEEl27TdRnrlveBDdKvqtwI2I7vy6EMWvuKETXsN8t9TA290q3ZRxyTDAwu5NLKqwTJi3CSVTNGqo4Xj+h30E4t4q7BQ=,iv:p4aKTvsMSSApUXhLM/HQttzr5PzdMnFtYlhJz/7PQtk=,tag:Lcy3Z9XPEBDo250AojLN/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
